export const regions = {
  "North America": {
    USD: "United States",
    CAD: "Canada",
    MXN: "Mexico",
  },
  "South America": {
    BRL: "Brazil",
    ARS: "Argentina",
    CLP: "Chile",
    COP: "Colombia",
    PEN: "Peru",
    VEF: "Venezuela",
    UYU: "Uruguay",
  },
  Europe: {
    EUR: "Eurozone Countries",
    GBP: "United Kingdom",
    CHF: "Switzerland",
    DKK: "Denmark",
    NOK: "Norway",
    SEK: "Sweden",
    PLN: "Poland",
    RUB: "Russia",
    CZK: "Czech Republic",
    HUF: "Hungary",
  },
  Asia: {
    CNY: "China",
    INR: "India",
    JPY: "Japan",
    KRW: "South Korea",
    SGD: "Singapore",
    THB: "Thailand",
    IDR: "Indonesia",
    PHP: "Philippines",
    MYR: "Malaysia",
    TWD: "Taiwan",
    BDT: "Bangladesh",
    PKR: "Pakistan",
    LKR: "Sri Lanka",
    MMK: "Myanmar",
    VND: "Vietnam",
    IRR: "Iran",
  },
  "Middle East": {
    AED: "United Arab Emirates",
    SAR: "Saudi Arabia",
    QAR: "Qatar",
    KWD: "Kuwait",
    BHD: "Bahrain",
    JOD: "Jordan",
    OMR: "Oman",
    LBP: "Lebanon",
    TND: "Tunisia",
  },
  Africa: {
    NGN: "Nigeria",
    KES: "Kenya",
    ZAR: "South Africa",
    GHS: "Ghana",
    MAD: "Morocco",
    ZMW: "Zambia",
    TZS: "Tanzania",
    UGX: "Uganda",
    NAD: "Namibia",
    BWP: "Botswana",
    MUR: "Mauritius",
    ETB: "Ethiopia",
    ZWL: "Zimbabwe",
    EGP: "Egypt",
  },
  Oceania: {
    AUD: "Australia",
    NZD: "New Zealand",
  },
};
